name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  IMAGE_NAME: johnhwhite/beanshell
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        run: |
          set -x
          docker build -t $IMAGE_NAME .
          echo 'print( "hello world" );' | docker run --rm -i $IMAGE_NAME | fgrep 'bsh % hello world'
      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          set -x
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u johnhwhite --password-stdin
          docker buildx build -t $IMAGE_NAME:latest --platform linux/amd64,linux/arm64/v8 --push .
          docker logout
